.TH BETTER-TOUCH 1 "June 2025" "Version 1.0.0" "User Commands"
.SH NAME
better-touch \- create a file and missing directories, like touch but smarter
.SH SYNOPSIS
.B better-touch
[\fIFILE\fR...]
.SH DESCRIPTION
\fBbetter-touch\fR is a small utility that behaves like the standard
\fItouch\fR command, but will also create any missing parent directories.
.SH OPTIONS
.HP
\fB\-h\fR, \fB\-\-help\fR
.IP
Print help
.HP
\fB\-V\fR, \fB\-\-version\fR
.IP
Print version