.TH BETTER-TOUCH 1 "June 2025" "Version 1.1.0" "User Commands"

.SH NAME
better-touch \- create a file and missing directories, like touch but smarter

.SH SYNOPSIS
.B better-touch
[\fIOPTIONS\fR] [\fIFILENAME\fR]...

.SH DESCRIPTION
\fBbetter-touch\fR is a small utility that behaves like the standard
\fItouch\fR command, but with added functionality. In addition to updating
file timestamps, it will also create any missing parent directories

.SH OPTIONS

.TP
\fB\-h\fR, \fB\-\-help\fR
Show help.

.TP
\fB\-V\fR, \fB\-\-version\fR
Display the current version.

.TP
\fB\-v\fR, \fB\-\-verbose\fR
Enable verbose output. Shows additional information about what the tool is doing.

.TP
\fB\-a\fR, \fB\-\-access-time\fR
Set the access time to the current time.

.TP
\fB\-t\fR \fITIME\fR, \fB\-\-time\fR \fITIME\fR
Set the access time to a specific time in ISO 8601 format.

.TP
\fB\-c\fR, \fB\-\-no-create\fR
Don't create a file if it does not exist. Only modify access time if the file is already present.

.SH AUTHOR
https://github.com/fatalus69.

.SH VERSION
1.1.0

.SH SEE ALSO
\fBtouch\fR(1), \fBmkdir\fR(1)
